### ISSUE TITLE
Add descriptive variable comments to the Conversational Search Starter Kit

### ISSUE THREAD

**Issue by andrewrfreed** [watson-developer-cloud/assistant-toolkit#137]
I suggest using self-documenting code where possible.

Here are suggested comments:
* discovery_project_id: You MUST change this value for your instance
* prompt: You MAY change this to do prompt engineering, but a default will be used by watsonx if you don’t pass a prompt here.
* query_text: You MAY change this to pass queries to Watson Discovery.  By default the Search action passes the user’s input.text directly.
* answer: Response object from Discovery query (https://cloud.ibm.com/apidocs/discovery-data#query)
* passages: Response object from Discovery query (https://cloud.ibm.com/apidocs/discovery-data#query)
* search_results: Response object from Discovery query (https://cloud.ibm.com/apidocs/discovery-data#query)
* snippet: Response object from Discovery query (https://cloud.ibm.com/apidocs/discovery-data#query)
* title: Response object from Discovery query (https://cloud.ibm.com/apidocs/discovery-data#query)
* discovery_date_version: <Seems old – what guidance for setting it?>

I also suggest the following:
* Remove the default `discovery_project_id` or set to an `xxxx-xxxxxxxx-xxxx` type of string.  By default it looks like it will work but you MUST change it from default.
* Is the 2022 date the correct value for `discovery_date_version`?  Can you include a reference to what the possible values are or a resource that suggests when/why to change them?

**Comment by jwm4** [comment]
These seem like good ideas.  Some thoughts on date versions:
- Discovery date versions are [documented in the release notes](https://cloud.ibm.com/docs/discovery-data?topic=discovery-data-release-notes).
- The current version there is `2023-03-31`, which includes a minor change to the JSON document ingestion API.  Since this kit does not do ingestion, it doesn't matter whether we move to `2023-03-31`.
- The previous version was `2020-08-30`, which had a change to the list enrichments API (which we also do not use), and the one before that was the original v2 API: `2019-11-29`.
- So none of the date version changes affect this kit, and the behavior would be the same for any existing date version.
- If you specify a date other than one of those listed above, you get the behavior for the last version _before_ the date you specify.  For example, specifying a date in 2022 gets you the `2020-08-30` behavior.
- The important thing though is not to specify a date version in the future, because then some breaking change in the API could happen that would cause the kit to stop working.

This seems like much more detail than this kit needs.  We might want to add the first bullet above (link to release notes), and leave it at that.

**Comment by rafael-nogueras** [comment]
This will be fixed in [this PR](https://github.com/watson-developer-cloud/assistant-toolkit/pull/139).

**Comment by jwm4** [comment]
Done!
